# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gopal-joshi/Programs/C++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gopal-joshi/Programs/C++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gopal-joshi/Programs/C++/CMakeFiles /home/gopal-joshi/Programs/C++/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gopal-joshi/Programs/C++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named F_Network

# Build rule for target.
F_Network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 F_Network
.PHONY : F_Network

# fast build rule for target.
F_Network/fast:
	$(MAKE) -f CMakeFiles/F_Network.dir/build.make CMakeFiles/F_Network.dir/build
.PHONY : F_Network/fast

#=============================================================================
# Target rules for targets named MarketPrice

# Build rule for target.
MarketPrice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MarketPrice
.PHONY : MarketPrice

# fast build rule for target.
MarketPrice/fast:
	$(MAKE) -f CMakeFiles/MarketPrice.dir/build.make CMakeFiles/MarketPrice.dir/build
.PHONY : MarketPrice/fast

#=============================================================================
# Target rules for targets named Linked_list

# Build rule for target.
Linked_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Linked_list
.PHONY : Linked_list

# fast build rule for target.
Linked_list/fast:
	$(MAKE) -f CMakeFiles/Linked_list.dir/build.make CMakeFiles/Linked_list.dir/build
.PHONY : Linked_list/fast

#=============================================================================
# Target rules for targets named array_union

# Build rule for target.
array_union: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 array_union
.PHONY : array_union

# fast build rule for target.
array_union/fast:
	$(MAKE) -f CMakeFiles/array_union.dir/build.make CMakeFiles/array_union.dir/build
.PHONY : array_union/fast

F_Network.o: F_Network.cpp.o

.PHONY : F_Network.o

# target to build an object file
F_Network.cpp.o:
	$(MAKE) -f CMakeFiles/F_Network.dir/build.make CMakeFiles/F_Network.dir/F_Network.cpp.o
.PHONY : F_Network.cpp.o

F_Network.i: F_Network.cpp.i

.PHONY : F_Network.i

# target to preprocess a source file
F_Network.cpp.i:
	$(MAKE) -f CMakeFiles/F_Network.dir/build.make CMakeFiles/F_Network.dir/F_Network.cpp.i
.PHONY : F_Network.cpp.i

F_Network.s: F_Network.cpp.s

.PHONY : F_Network.s

# target to generate assembly for a file
F_Network.cpp.s:
	$(MAKE) -f CMakeFiles/F_Network.dir/build.make CMakeFiles/F_Network.dir/F_Network.cpp.s
.PHONY : F_Network.cpp.s

Linked_list.o: Linked_list.cpp.o

.PHONY : Linked_list.o

# target to build an object file
Linked_list.cpp.o:
	$(MAKE) -f CMakeFiles/Linked_list.dir/build.make CMakeFiles/Linked_list.dir/Linked_list.cpp.o
.PHONY : Linked_list.cpp.o

Linked_list.i: Linked_list.cpp.i

.PHONY : Linked_list.i

# target to preprocess a source file
Linked_list.cpp.i:
	$(MAKE) -f CMakeFiles/Linked_list.dir/build.make CMakeFiles/Linked_list.dir/Linked_list.cpp.i
.PHONY : Linked_list.cpp.i

Linked_list.s: Linked_list.cpp.s

.PHONY : Linked_list.s

# target to generate assembly for a file
Linked_list.cpp.s:
	$(MAKE) -f CMakeFiles/Linked_list.dir/build.make CMakeFiles/Linked_list.dir/Linked_list.cpp.s
.PHONY : Linked_list.cpp.s

MarketPrice.o: MarketPrice.cpp.o

.PHONY : MarketPrice.o

# target to build an object file
MarketPrice.cpp.o:
	$(MAKE) -f CMakeFiles/MarketPrice.dir/build.make CMakeFiles/MarketPrice.dir/MarketPrice.cpp.o
.PHONY : MarketPrice.cpp.o

MarketPrice.i: MarketPrice.cpp.i

.PHONY : MarketPrice.i

# target to preprocess a source file
MarketPrice.cpp.i:
	$(MAKE) -f CMakeFiles/MarketPrice.dir/build.make CMakeFiles/MarketPrice.dir/MarketPrice.cpp.i
.PHONY : MarketPrice.cpp.i

MarketPrice.s: MarketPrice.cpp.s

.PHONY : MarketPrice.s

# target to generate assembly for a file
MarketPrice.cpp.s:
	$(MAKE) -f CMakeFiles/MarketPrice.dir/build.make CMakeFiles/MarketPrice.dir/MarketPrice.cpp.s
.PHONY : MarketPrice.cpp.s

array_union.o: array_union.cpp.o

.PHONY : array_union.o

# target to build an object file
array_union.cpp.o:
	$(MAKE) -f CMakeFiles/array_union.dir/build.make CMakeFiles/array_union.dir/array_union.cpp.o
.PHONY : array_union.cpp.o

array_union.i: array_union.cpp.i

.PHONY : array_union.i

# target to preprocess a source file
array_union.cpp.i:
	$(MAKE) -f CMakeFiles/array_union.dir/build.make CMakeFiles/array_union.dir/array_union.cpp.i
.PHONY : array_union.cpp.i

array_union.s: array_union.cpp.s

.PHONY : array_union.s

# target to generate assembly for a file
array_union.cpp.s:
	$(MAKE) -f CMakeFiles/array_union.dir/build.make CMakeFiles/array_union.dir/array_union.cpp.s
.PHONY : array_union.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... F_Network"
	@echo "... MarketPrice"
	@echo "... Linked_list"
	@echo "... array_union"
	@echo "... F_Network.o"
	@echo "... F_Network.i"
	@echo "... F_Network.s"
	@echo "... Linked_list.o"
	@echo "... Linked_list.i"
	@echo "... Linked_list.s"
	@echo "... MarketPrice.o"
	@echo "... MarketPrice.i"
	@echo "... MarketPrice.s"
	@echo "... array_union.o"
	@echo "... array_union.i"
	@echo "... array_union.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

